import LazyDemo from "@/components/lazy-demo";
import LossCalculator from "@/components/loss-calculator";

function GrowthChart() {
  return <div className="growth"><div className="chart-top"><span>ATENCIÓN MÁS ORDENADA</span><span className="example">Ilustración conceptual</span></div><div className="chart-number">Más claridad.<br /><em>Más oportunidades.</em></div><svg viewBox="0 0 680 240" role="img" aria-label="Gráfica ascendente ilustrativa, sin datos reales"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#168aff" stopOpacity=".24" /><stop offset="1" stopColor="#168aff" stopOpacity="0" /></linearGradient></defs>{[55,110,165,220].map((y)=><path key={y} d={`M0 ${y}H680`} stroke="#dde5ea" strokeDasharray="4 7" />)}<path d="M0 218L70 208L140 184L210 193L280 151L350 132L420 145L490 91L560 65L630 24L680 10V240H0Z" fill="url(#fill)" /><path className="chart-line" d="M0 218L70 208L140 184L210 193L280 151L350 132L420 145L490 91L560 65L630 24L680 10" fill="none" stroke="#087bff" strokeWidth="4" strokeLinejoin="round" /></svg><div className="chart-axis"><span>Diagnóstico</span><span>Implementación →</span></div></div>;
}

const botFeatures = [["01","Atención continua","Responde preguntas frecuentes aunque el equipo esté ocupado o fuera del horario habitual."],["02","Información consistente","Servicios, precios, horarios y ubicación configurados específicamente para cada empresa."],["03","Solicitudes ordenadas","Captura datos para pedidos, reservas, cotizaciones o seguimiento comercial."],["04","Escalamiento humano","Cuando una conversación necesita criterio o confirmación, puede pasar a una persona."]];
const aiFeatures = [["01","Cotizaciones y documentos","Preparamos borradores, resúmenes y documentos a partir de información autorizada."],["02","Seguimiento comercial","Organizamos consultas y próximos pasos para que ninguna tarea importante quede olvidada."],["03","Flujos internos","Identificamos procesos repetitivos y configuramos herramientas simples para reducir trabajo manual."]];
const industries = ["Hoteles","Turismo y tours","Restaurantes","Talleres","Salones y estética","Tiendas","Servicios profesionales","Empresas de servicios"];

export default function Home(){
  return <main>
    <header className="top"><a href="#inicio" className="brand" aria-label="MetaBot CR, inicio"><span className="brand-icon">m</span><span>MetaBot <b>CR</b></span></a><nav aria-label="Navegación principal"><a href="#soluciones">Soluciones</a><a href="#proceso">Proceso</a><a href="#demo">Demostración</a><a href="#contacto">Contacto</a></nav><a className="button small" href="#contacto">Solicitar diagnóstico <span>↗</span></a></header>

    <section className="hero wrap" id="inicio"><div className="eyebrow"><span /> INTELIGENCIA ARTIFICIAL PARA EMPRESAS</div><h1>Modernizamos negocios<br /><em>con inteligencia artificial.</em></h1><p className="lead">MetaBot CR desarrolla e implementa soluciones de automatización para ayudar a empresas en crecimiento a atender mejor, ahorrar tiempo y organizar sus procesos sin conocimientos técnicos.</p><div className="actions"><a className="button" href="#contacto">Solicitar diagnóstico <span>↗</span></a><a className="text-link" href="#soluciones">Ver soluciones ↓</a></div><p className="micro">Implementación · Configuración · Automatización · Acompañamiento</p><div className="hero-stage"><GrowthChart /><div className="mini-chat"><div className="mini-head"><span className="bot-symbol">m</span><div>MetaBot CR<small>Automatización aplicada al negocio</small></div><span className="online" /></div><p className="sample-user">¿Me pueden ayudar con una cotización?</p><p className="sample-bot">Claro. Contame qué servicio necesitás y te indico los siguientes pasos.</p><div className="chat-tags"><span>Respuesta inmediata</span><span>Proceso claro</span></div></div></div></section>

    <section className="regional" aria-label="Visión regional"><div className="wrap regional-grid"><div><span className="eyebrow">COSTA RICA · VISIÓN CENTROAMÉRICA</span><h2>Tecnología pensada para los negocios de nuestra región.</h2></div><p>MetaBot CR nace con enfoque en Costa Rica y una visión de expansión progresiva hacia Nicaragua y otros mercados de Centroamérica. Acercamos herramientas que suelen parecer complejas a empresas que necesitan soluciones prácticas, claras y fáciles de utilizar.</p></div><div className="regional-route wrap"><span>Costa Rica</span><i>→</i><span>Nicaragua</span><i>→</i><span>Centroamérica</span></div></section>

    <section className="wrap section" id="soluciones"><div className="section-heading"><span className="eyebrow">SOLUCIONES EMPRESARIALES</span><h2>Dos formas de incorporar<br /><em>inteligencia artificial.</em></h2><p>Elegí el servicio que responde a la necesidad actual de tu empresa. Se cotizan e implementan por separado.</p></div><div className="service-grid"><article className="service-card service-card-primary"><div className="service-kicker">SERVICIO 01 · CANAL DE ATENCIÓN</div><h3>Bot de WhatsApp con Inteligencia Artificial</h3><p>Una solución para empresas que reciben consultas, solicitudes, reservas, pedidos o cotizaciones mediante WhatsApp.</p><ul>{["Atención automática 24/7","Precios, horarios, ubicación y servicios","Captura de datos y solicitudes","Reservas, pedidos o cotizaciones","Seguimiento de prospectos","Transferencia a una persona"].map((item)=><li key={item}>{item}</li>)}</ul><a className="button" href="#demo">Conocer WhatsApp IA <span>↗</span></a></article><article className="service-card service-card-secondary"><div className="service-kicker">SERVICIO 02 · OPERACIÓN INTERNA</div><h3>Inteligencia Artificial para Empresas</h3><p>Analizamos procesos repetitivos e implementamos herramientas de IA para simplificar tareas administrativas y operativas.</p><ul>{["Cotizaciones y documentos","Correos y agenda","Seguimiento comercial","Reportes y clasificación","Consultas internas","Flujos de trabajo"].map((item)=><li key={item}>{item}</li>)}</ul><a className="button light" href="#ia-empresas">Solicitar diagnóstico de automatización <span>↗</span></a></article></div></section>

    <section className="wrap section bot-section" id="whatsapp-ia"><div className="section-heading"><span className="eyebrow">SERVICIO 01 · WHATSAPP IA</span><h2>Una atención más clara,<br /><em>sin ampliar tu jornada.</em></h2><p>El bot se configura con la información de cada negocio para responder lo habitual, ordenar solicitudes y dejar a tu equipo las conversaciones que requieren criterio.</p></div><div className="feature-grid">{botFeatures.map(([n,title,body])=><article key={n}><span className="step">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="diagnostic section" id="diagnostico"><div className="wrap"><span className="eyebrow">DIAGNÓSTICO ESTIMADO DE OPORTUNIDADES DE ATENCIÓN</span><h2>Entendé qué ocurre<br /><em>cuando una consulta espera.</em></h2><p>Usá tus propios datos para explorar un escenario antes y después de automatizar. La herramienta ofrece únicamente una estimación basada en los datos ingresados; no representa una proyección ni una garantía de ventas.</p><div className="comparison"><article><span>SIN AUTOMATIZACIÓN</span><h3>La respuesta depende de la disponibilidad del equipo.</h3><p>La consulta espera, el seguimiento se acumula y el cliente puede continuar su búsqueda en otro lugar.</p></article><article><span>CON EL BOT CONFIGURADO</span><h3>Una primera respuesta mientras el equipo se organiza.</h3><p>El bot orienta, recopila lo necesario y deriva a una persona cuando corresponde. La venta nunca se promete automáticamente.</p></article></div><LossCalculator /></div></section>

    <section className="vision" id="proceso"><div className="wrap vision-grid"><div><span className="eyebrow">CÓMO TRABAJAMOS</span><h2>Un proceso claro<br />desde el diagnóstico<br /><em>hasta la implementación.</em></h2><p>La tecnología se incorpora de forma gradual, con alcance definido y revisión antes de activar cada automatización.</p></div><div className="process-list">{[["01","Diagnóstico","Entendemos cómo funciona actualmente el negocio y qué procesos consumen más tiempo."],["02","Diseño de la solución","Definimos qué tareas pueden automatizarse y qué tecnología se utilizará."],["03","Implementación","Configuramos las herramientas, automatizaciones e integraciones necesarias."],["04","Pruebas y acompañamiento","Probamos el funcionamiento y acompañamos al negocio durante la puesta en marcha."]].map(([n,title,text])=><article key={n}><strong>{n}</strong><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

    <section className="wrap section trust"><div className="section-heading"><span className="eyebrow">IMPLEMENTACIÓN PROFESIONAL</span><h2>La tecnología no debería<br /><em>complicar tu negocio.</em></h2><p>Las empresas no deberían necesitar un departamento de programación para aprovechar la inteligencia artificial. MetaBot CR configura la tecnología y la adapta al funcionamiento de cada negocio.</p></div><div className="trust-grid">{[["Configuración personalizada","Cada implementación se adapta a la información y los procesos autorizados."],["Acompañamiento","El cliente recibe orientación y un alcance de soporte claro."],["Control humano","Las situaciones que necesitan criterio pueden transferirse a una persona."],["Implementación gradual","Comenzamos por los procesos donde la automatización aporta utilidad operativa."]].map(([title,text])=><article key={title}><span className="trust-mark">✓</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="wrap section demo-section" id="demo"><div><span className="eyebrow">DEMOSTRACIÓN INTERACTIVA</span><h2>Probá cómo podría funcionar<br /><em>una atención automatizada.</em></h2><p>Esta simulación muestra un ejemplo de cómo un asistente puede atender consultas frecuentes de un negocio.</p><div className="demo-note"><strong>Importante:</strong> esta demostración no envía mensajes, no genera pedidos ni pagos y no confirma disponibilidad real.</div></div><LazyDemo /></section>

    <section className="industries"><div className="wrap section"><span className="eyebrow">SOLUCIONES APLICABLES A</span><h2>Distintos sectores.<br /><em>Una implementación a la medida.</em></h2><div className="industry-grid">{industries.map((industry)=><div key={industry}><span>↗</span>{industry}</div>)}</div><p className="industry-note">La aplicación concreta depende del proceso, la información disponible y el alcance definido con cada empresa. No afirmamos experiencia previa en un sector hasta contar con una implementación verificable.</p></div></section>

    <section className="enterprise-section" id="ia-empresas"><div className="wrap section"><span className="eyebrow">SERVICIO 02 · IA PARA EMPRESAS</span><h2>Nosotros configuramos la tecnología.<br /><em>Tu empresa simplemente la utiliza.</em></h2><p className="enterprise-lead">Analizamos una necesidad concreta y construimos una solución práctica, sin obligarte a cambiar todo tu sistema.</p><div className="feature-grid">{aiFeatures.map(([n,title,body])=><article key={n}><span className="step">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="enterprise-quote"><h3>Simple de contratar. Adaptado a tu empresa.</h3><p>Recibís una propuesta por proyecto con instalación, licencias y soporte detallados. El plazo depende del alcance y los accesos disponibles.</p></div><a className="button" href="#contacto">Solicitar diagnóstico de automatización <span>↗</span></a></div></section>

    <section className="wrap section consulting"><div className="consulting-card"><div><span className="eyebrow">CONSULTORÍA TECNOLÓGICA</span><h2>No todas las empresas necesitan la misma automatización.</h2><p>Por eso comenzamos entendiendo el funcionamiento del negocio antes de recomendar una solución. La implementación puede crecer de forma progresiva.</p></div><a className="button" href="#contacto">Solicitar diagnóstico inicial <span>↗</span></a></div></section>

    <section className="wrap section faq"><span className="eyebrow">TRANSPARENCIA</span><h2>Lo importante,<br /><em>sin letra pequeña.</em></h2><details><summary>¿El bot garantiza más ventas?</summary><p>No. Puede reducir esperas y facilitar solicitudes. Las ventas dependen de la demanda, la oferta y la atención del negocio.</p></details><details><summary>¿Tengo que contratar los dos servicios?</summary><p>No. El bot de WhatsApp y la instalación de IA para empresas se cotizan y contratan por separado.</p></details><details><summary>¿MetaBot CR ya opera en toda Centroamérica?</summary><p>El enfoque inicial es Costa Rica, con una visión de expansión progresiva hacia Nicaragua y otros mercados de la región.</p></details><details><summary>¿Qué está disponible hoy?</summary><p>Podés explorar la demostración y la calculadora. La conexión real con WhatsApp y las integraciones empresariales requieren configuración, permisos y pruebas.</p></details></section>

    <section className="closing" id="contacto"><span className="eyebrow">COSTA RICA · VISIÓN CENTROAMÉRICA</span><h2>Prepará tu empresa<br />para la nueva forma <em>de trabajar.</em></h2><p>La inteligencia artificial puede incorporarse progresivamente a los procesos de una empresa. El primer paso es identificar dónde puede aportar mayor valor.</p><div className="actions"><a className="button" href="#diagnostico">Hablar con MetaBot CR <span>↗</span></a><a className="text-link" href="#diagnostico">Solicitar diagnóstico ↓</a></div></section>

    <footer className="wrap"><div><a className="brand" href="#inicio"><span className="brand-icon">m</span><span>MetaBot <b>CR</b></span></a><p>Inteligencia artificial y automatización para empresas.</p></div><nav aria-label="Enlaces del pie de página"><a href="#soluciones">Soluciones</a><a href="#whatsapp-ia">WhatsApp IA</a><a href="#ia-empresas">IA para empresas</a><a href="#demo">Demostración</a><a href="#contacto">Contacto</a></nav><small>Costa Rica · Visión Centroamérica<br />MetaBot CR es una marca independiente, sin afiliación con Meta.</small></footer>
  </main>;
}
