import LazyDemo from "@/components/lazy-demo";
import LossCalculator from "@/components/loss-calculator";

function GrowthChart() {
  return <div className="growth"><div className="chart-top"><span>CONVERSACIONES ATENDIDAS</span><span className="example">Ejemplo ilustrativo</span></div><div className="chart-number">Más atención.<br/><em>Más oportunidades.</em></div><svg viewBox="0 0 680 240" role="img" aria-label="Gráfica ascendente ilustrativa, sin datos reales"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#168aff" stopOpacity=".25"/><stop offset="1" stopColor="#168aff" stopOpacity="0"/></linearGradient></defs>{[55,110,165,220].map(y=><path key={y} d={`M0 ${y}H680`} stroke="#dde5ea" strokeDasharray="4 7"/>)}<path d="M0 218L70 208L140 184L210 193L280 151L350 132L420 145L490 91L560 65L630 24L680 10V240H0Z" fill="url(#fill)"/><path className="chart-line" d="M0 218L70 208L140 184L210 193L280 151L350 132L420 145L490 91L560 65L630 24L680 10" fill="none" stroke="#087bff" strokeWidth="4" strokeLinejoin="round"/></svg><div className="chart-axis"><span>Inicio</span><span>Evolución ilustrativa →</span></div></div>;
}

export default function Home(){
return <main>
  <header className="top"><a href="#" className="brand"><span className="brand-icon">m</span>MetaBot</a><nav aria-label="Navegación"><a href="#bot">Bot WhatsApp</a><a href="#diagnostico">Calculá tu oportunidad</a><a href="#ia-empresas">Instalación de IA</a></nav><a className="button small" href="#demo">Probar el bot <span>↗</span></a></header>
  <section className="hero wrap" id="bot"><div className="eyebrow"><span/> SERVICIO PRINCIPAL · METABOT CR</div><h1>Bot de WhatsApp con IA.<br/><em>Tu negocio no espera.</em></h1><p className="lead">Automatizá la atención de tu negocio en Costa Rica. Mientras atendés el local o descansás, tu bot puede responder consultas y recoger solicitudes de compra. Que un “¿cuánto cuesta?” no se quede sin respuesta.</p><div className="actions"><a className="button" href="#demo">Probar el bot ↗</a><a className="text-link" href="#diagnostico">¿Cuánto vale responder a tiempo? ↓</a></div><p className="micro">También para Nicaragua y Latinoamérica. Cotización del servicio en USD.</p>
  <div className="hero-stage"><GrowthChart/><div className="mini-chat"><div className="mini-head"><span className="bot-symbol">m</span><div>MetaBot<small>Una conversación de ejemplo</small></div><span className="online"/></div><p className="sample-user">¿Me preparan un pedido para recoger?</p><p className="sample-bot">¡Claro! Contame qué te gustaría pedir y te ayudo paso a paso.</p><div className="chat-tags"><span>Consulta entendida</span><span>Atención cercana</span></div></div></div>
  </section>
  <div className="business-strip"><span>AUTOMATIZAR WHATSAPP PARA TU NEGOCIO</span><div>Restaurantes <b>✳</b> Hoteles <b>✳</b> Tiendas <b>✳</b> Talleres <b>✳</b> Salones</div></div>
  <section className="wrap section" id="modelo"><div className="section-heading"><span className="eyebrow">BOT WHATSAPP · TIEMPO, OPORTUNIDADES, CONFIANZA</span><h2>Que tu atención crezca.<br/><em>No tu jornada.</em></h2><p>Tu próximo cliente puede escribir cuando estás más ocupado. Dale un primer paso claro para comprar, incluso fuera del horario del local.</p></div><div className="feature-grid">{[["24/7","Mientras dormís, la conversación sigue.","Con el servicio activado, el bot puede explicar productos y recibir solicitudes de madrugada. Vos retomás lo que requiere confirmación. Sujeto a disponibilidad de las plataformas."],["TIEMPO","Dejá de escribir lo mismo veinte veces.","Horarios, ubicación y precios: las preguntas repetidas consumen minutos. Reservá tu atención para asesorar, entregar pedidos y cuidar a tus clientes."],["VENTAS","Menos oportunidades que se enfrían.","Una consulta atendida puede convertirse en el siguiente pedido. El bot reduce la espera; el cierre depende de tu oferta, disponibilidad y decisión del cliente."],["IMAGEN","Un negocio que se siente más profesional.","Información consistente, trato cordial y un siguiente paso claro. Una experiencia cuidada ayuda a construir confianza en tu nombre."],["INVERSIÓN","¿Puede pagarse solo? Hacé la cuenta.","Sí, si el margen de las ventas adicionales que ayuda a conseguir cubre instalación, consumo y mantenimiento. No necesitás adivinar: calculá tu punto de equilibrio abajo."],["CONTROL","Automatizá sin perder el trato humano.","Definí qué información puede dar y cuándo debe intervenir tu equipo. Un precio o una disponibilidad sin confirmar no debería convertirse en una promesa."]].map(([n,title,body])=><article key={n}><span className="step">{n} ↗</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="diagnostic section" id="diagnostico"><div className="wrap"><span className="eyebrow">DIAGNÓSTICO DEL BOT · SIMULACIÓN EDITABLE</span><h2>El costo de no contestar<br/><em>no aparece en la factura.</em></h2><p>¿Cuántas consultas quedan pendientes cuando estás ocupado? Probá un escenario con tus propios datos y mirá qué tendría que pasar para recuperar la inversión.</p><div className="comparison"><article><span>SIN AUTOMATIZACIÓN</span><h3>Todo depende de que estés disponible.</h3><p>La consulta espera → el cliente puede buscar otra opción → tenés que retomar la conversación después.</p></article><article><span>CON EL BOT CONFIGURADO</span><h3>Una primera respuesta, sin esperar al dueño.</h3><p>El bot atiende la consulta → recoge lo necesario → tu equipo confirma lo que corresponde. Responder no garantiza retener ni vender.</p></article></div><LossCalculator/></div></section>
  <section className="vision" id="resultados"><div className="wrap vision-grid"><div><span className="eyebrow">02 / MÁS ALLÁ DEL “HOLA”</span><h2>Hacé espacio<br/>para lo que<br/><em>viene.</em></h2><p>Una atención más ordenada empieza por una conversación bien resuelta. Nuestro objetivo: ayudarte a dedicar más tiempo a tu negocio.</p><a className="button light" href="#demo">Mirá la experiencia ↗</a></div><div className="bars-card"><div className="chart-top"><span>OPORTUNIDADES DE ATENCIÓN</span><span>Ilustración</span></div><div className="bars">{[22,31,28,43,50,62,70,86,100].map((h,i)=><div key={i} style={{height:`${h}%`,animationDelay:`${i*80}ms`}}/>)}</div><p>Un camino hacia una mejor atención.</p><small>Visualización conceptual. No representa ventas ni resultados garantizados.</small></div></div></section>
  <section className="wrap section demo-section" id="demo"><div><span className="eyebrow">BOT WHATSAPP · PROBALO VOS</span><h2>Menos explicaciones.<br/><em>Más conversación.</em></h2><p>Pedí un casado de carne, elegí recoger y escribí tu nombre. Después seleccioná una forma de pago.</p><div className="demo-note">Esta demo usa reglas y datos ficticios. No tiene IA conectada, no envía pedidos ni pagos y no confirma disponibilidad real. El servicio real requiere configuración y pruebas.</div></div><LazyDemo/></section>
  <section className="wrap section" id="planes"><span className="eyebrow">SOLO BOT WHATSAPP · COTIZACIÓN EN USD</span><h2>Una inversión con<br/><em>números claros.</em></h2><p>La propuesta separa configuración inicial, mantenimiento y consumo de Meta e IA. El costo depende de lo que el bot deba resolver y de tu volumen de consultas. Sin tarifas inventadas ni promesas de ventas.</p><a className="button" href="#diagnostico">Calculá cuándo se recupera ↗</a></section>
  <section className="enterprise-section" id="ia-empresas"><div className="wrap section"><span className="eyebrow">SERVICIO ADICIONAL E INDEPENDIENTE · SIN CONTRATAR EL BOT</span><h2>Instalación de inteligencia artificial<br/><em>para tu empresa.</em></h2><p className="enterprise-lead">Vos conocés tu trabajo. Nosotros nos encargamos de la parte técnica.</p><p>Convertí una tarea repetitiva en tu primer uso práctico de IA: resumir documentos, preparar borradores o consultar información autorizada. Empezamos con una necesidad concreta, sin complicarte con herramientas que no ocupás.</p><div className="feature-grid">{[["01","Nos contás qué te quita tiempo.","Definimos una tarea, los datos permitidos y el resultado que necesitás."],["02","Configuramos y probamos.","Seleccionamos la herramienta y preparamos el asistente con los accesos que autoricés."],["03","Te enseñamos a usarlo.","Recibís orientación y un alcance de soporte claro. Vos revisás los resultados importantes."]].map(([n,t,p])=><article key={n}><span className="step">{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><div className="enterprise-quote"><h3>Simple de contratar. Adaptado a tu empresa.</h3><p>Una propuesta por proyecto en USD, con instalación, licencias y soporte detallados. El plazo depende del alcance y los accesos disponibles. No necesitás contratar WhatsApp ni cambiar todo tu sistema.</p></div><h3>Es hora de que tu negocio avance hacia la tecnología.</h3><p>Una visión de nivel empresarial, a la medida de una pyme: procesos definidos, permisos y pruebas antes de activar. La aspiración es acercarte a la forma de trabajar de grandes empresas de Estados Unidos y Europa; no implica certificaciones ni equivalencia con sus sistemas.</p></div></section>
  <section className="wrap section faq"><span className="eyebrow">ANTES DE ELEGIR</span><h2>Lo importante,<br/><em>sin letra pequeña.</em></h2><details><summary>¿El bot garantiza más ventas?</summary><p>No. Puede reducir esperas y facilitar solicitudes. Las ventas dependen de la demanda, tu oferta y tu atención. La calculadora muestra supuestos editables, no resultados prometidos.</p></details><details><summary>¿Tengo que contratar los dos servicios?</summary><p>No. El bot para WhatsApp y la instalación de IA para empresas se cotizan y contratan por separado.</p></details><details><summary>¿Solo funciona para Costa Rica?</summary><p>El servicio está orientado a Costa Rica y también contempla Nicaragua y otros países de Latinoamérica. Monedas, métodos de pago y alcance se definen con cada negocio.</p></details><details><summary>¿Qué está disponible hoy?</summary><p>Podés explorar la demostración y simular escenarios. El bot real con IA, la conexión con WhatsApp y las integraciones empresariales necesitan configuración y verificación antes de usarse con clientes.</p></details></section>
  <section className="closing"><span className="eyebrow">CONVERSACIONES QUE ABREN PUERTAS</span><h2>Tu siguiente paso<br/>empieza con un <em>hola.</em></h2><a className="button" href="#demo">Probar MetaBot ↗</a></section><footer className="wrap"><a className="brand" href="#">MetaBot</a><p>Hecho para negocios de Latinoamérica.</p><small>MetaBot es un proyecto independiente, sin afiliación con Meta ni Intercom.</small></footer>
</main>;
}
