export const dynamic = "force-dynamic";

import SalesLeadForm from "@/components/lead-form";
import { isPublicLeadCaptureEnabled } from "@/lib/marketing/leads";
import LazyDemo from "@/components/lazy-demo";
import LossCalculator from "@/components/loss-calculator";

const botFeatures = [["01","Atención continua","Responde preguntas frecuentes aunque el equipo esté ocupado o fuera del horario habitual."],["02","Información consistente","Servicios, precios, horarios y ubicación configurados específicamente para cada empresa."],["03","Solicitudes ordenadas","Captura datos para pedidos, reservas, cotizaciones o seguimiento comercial."],["04","Escalamiento humano","Cuando una conversación necesita criterio o confirmación, puede pasar a una persona."]];
const aiFeatures = [["01","Cotizaciones y documentos","Preparamos borradores, resúmenes y documentos a partir de información autorizada."],["02","Seguimiento comercial","Organizamos consultas y próximos pasos para que ninguna tarea importante quede olvidada."],["03","Flujos internos","Identificamos procesos repetitivos y configuramos herramientas simples para reducir trabajo manual."]];
const industries = ["Hoteles","Turismo y tours","Restaurantes","Talleres","Salones y estética","Tiendas","Servicios profesionales","Empresas de servicios"];

export default function Home(){
  return <main>
    <header className="top"><a href="#inicio" className="brand" aria-label="MetaBot CR, inicio"><span className="brand-icon">m</span><span>MetaBot <b>CR</b></span></a><nav aria-label="Navegación principal"><a href="#soluciones">Soluciones</a><a href="#proceso">Proceso</a><a href="#demo">Demostración</a><a href="#planes">Planes</a><a href="#contacto">Contacto</a></nav><a className="button small" href="#contacto">Solicitar diagnóstico <span>↗</span></a></header>

    <section className="hero wrap" id="inicio"><div className="eyebrow"><span /> INTELIGENCIA ARTIFICIAL PARA EMPRESAS</div><h1>Tu negocio recibe consultas.<br /><em>MetaBot te ayuda a organizarlas.</em></h1><p className="lead">Estamos construyendo una plataforma de atención y automatización para negocios de Costa Rica. Probá nuestra demostración y solicitá una evaluación antes de contratar una integración.</p><div className="actions"><a className="button" href="#contacto">Solicitar diagnóstico <span>↗</span></a><a className="text-link" href="#demo">Probar demostración ↓</a></div><p className="micro">Implementación · Configuración · Automatización · Acompañamiento</p><div className="demo-note" style={{marginTop:28}}>Probá la demostración interactiva más abajo: no muestra ventas inventadas, no envía mensajes a clientes y no confirma reservaciones reales.</div></section>

    <section className="regional" aria-label="Visión regional"><div className="wrap regional-grid"><div><span className="eyebrow">COSTA RICA · VISIÓN CENTROAMÉRICA</span><h2>Tecnología pensada para los negocios de nuestra región.</h2></div><p>MetaBot CR nace con enfoque en Costa Rica y una visión de expansión progresiva hacia Nicaragua y otros mercados de Centroamérica. Acercamos herramientas que suelen parecer complejas a empresas que necesitan soluciones prácticas, claras y fáciles de utilizar.</p></div><div className="regional-route wrap"><span>Costa Rica</span><i>→</i><span>Nicaragua</span><i>→</i><span>Centroamérica</span></div></section>

    <section className="wrap section" id="soluciones"><div className="section-heading"><span className="eyebrow">SOLUCIONES EMPRESARIALES</span><h2>Dos formas de incorporar<br /><em>inteligencia artificial.</em></h2><p>Elegí el servicio que responde a la necesidad actual de tu empresa. Se cotizan e implementan por separado.</p></div><div className="service-grid"><article className="service-card service-card-primary"><div className="service-kicker">SERVICIO 01 · CANAL DE ATENCIÓN</div><h3>Asistente para atención por WhatsApp</h3><p>Preparamos una solución para responder consultas con la información real del negocio. La conexión oficial de WhatsApp requiere aprobación y pruebas antes de activarse.</p><ul>{["Demostración interactiva disponible","Consulta del catálogo configurado","Historial de conversaciones en desarrollo","Integración oficial de Meta pendiente de autorización","Gestión de solicitudes por etapas","Intervención humana prevista en el sistema"].map((item)=><li key={item}>{item}</li>)}</ul><a className="button" href="#demo">Conocer WhatsApp IA <span>↗</span></a></article><article className="service-card service-card-secondary"><div className="service-kicker">SERVICIO 02 · OPERACIÓN INTERNA</div><h3>Inteligencia Artificial para Empresas</h3><p>Analizamos procesos repetitivos e implementamos herramientas de IA para simplificar tareas administrativas y operativas.</p><ul>{["Diagnóstico de procesos y necesidades","Propuestas de automatización a medida","Integraciones sujetas a revisión técnica","Planificación de tareas y seguimiento","Revisión de permisos y seguridad","Desarrollo gradual verificable"].map((item)=><li key={item}>{item}</li>)}</ul><a className="button light" href="#ia-empresas">Solicitar diagnóstico de automatización <span>↗</span></a></article></div></section>

    <section className="wrap section bot-section" id="whatsapp-ia"><div className="section-heading"><span className="eyebrow">SERVICIO 01 · WHATSAPP IA</span><h2>Una atención más clara,<br /><em>sin ampliar tu jornada.</em></h2><p>El bot se configura con la información de cada negocio para responder lo habitual, ordenar solicitudes y dejar a tu equipo las conversaciones que requieren criterio.</p></div><div className="feature-grid">{botFeatures.map(([n,title,body])=><article key={n}><span className="step">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="diagnostic section" id="diagnostico"><div className="wrap"><span className="eyebrow">DIAGNÓSTICO ESTIMADO DE OPORTUNIDADES DE ATENCIÓN</span><h2>Entendé qué ocurre<br /><em>cuando una consulta espera.</em></h2><p>Usá tus propios datos para explorar un escenario antes y después de automatizar. La herramienta ofrece únicamente una estimación basada en los datos ingresados; no representa una proyección ni una garantía de ventas.</p><div className="comparison"><article><span>SIN AUTOMATIZACIÓN</span><h3>La respuesta depende de la disponibilidad del equipo.</h3><p>La consulta espera, el seguimiento se acumula y el cliente puede continuar su búsqueda en otro lugar.</p></article><article><span>CON EL BOT CONFIGURADO</span><h3>Una primera respuesta mientras el equipo se organiza.</h3><p>El bot orienta, recopila lo necesario y deriva a una persona cuando corresponde. La venta nunca se promete automáticamente.</p></article></div><LossCalculator /></div></section>

    <section className="vision" id="proceso"><div className="wrap vision-grid"><div><span className="eyebrow">CÓMO TRABAJAMOS</span><h2>Un proceso claro<br />desde el diagnóstico<br /><em>hasta la implementación.</em></h2><p>La tecnología se incorpora de forma gradual, con alcance definido y revisión antes de activar cada automatización.</p></div><div className="process-list">{[["01","Diagnóstico","Entendemos cómo funciona actualmente el negocio y qué procesos consumen más tiempo."],["02","Diseño de la solución","Definimos qué tareas pueden automatizarse y qué tecnología se utilizará."],["03","Implementación","Configuramos las herramientas, automatizaciones e integraciones necesarias."],["04","Pruebas y acompañamiento","Probamos el funcionamiento y acompañamos al negocio durante la puesta en marcha."]].map(([n,title,text])=><article key={n}><strong>{n}</strong><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

    <section className="wrap section trust"><div className="section-heading"><span className="eyebrow">IMPLEMENTACIÓN PROFESIONAL</span><h2>La tecnología no debería<br /><em>complicar tu negocio.</em></h2><p>Las empresas no deberían necesitar un departamento de programación para aprovechar la inteligencia artificial. MetaBot CR configura la tecnología y la adapta al funcionamiento de cada negocio.</p></div><div className="trust-grid">{[["Configuración personalizada","Cada implementación se adapta a la información y los procesos autorizados."],["Acompañamiento","El cliente recibe orientación y un alcance de soporte claro."],["Control humano","Las situaciones que necesitan criterio pueden transferirse a una persona."],["Implementación gradual","Comenzamos por los procesos donde la automatización aporta utilidad operativa."]].map(([title,text])=><article key={title}><span className="trust-mark">✓</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="wrap section demo-section" id="demo"><div><span className="eyebrow">DEMOSTRACIÓN INTERACTIVA</span><h2>Probá cómo podría funcionar<br /><em>una atención automatizada.</em></h2><p>Esta simulación muestra un ejemplo de cómo un asistente puede atender consultas frecuentes de un negocio.</p><div className="demo-note"><strong>Importante:</strong> esta demostración no envía mensajes, no genera pedidos ni pagos y no confirma disponibilidad real.</div></div><LazyDemo /></section>

    <section className="industries"><div className="wrap section"><span className="eyebrow">SOLUCIONES APLICABLES A</span><h2>Distintos sectores.<br /><em>Una implementación a la medida.</em></h2><div className="industry-grid">{industries.map((industry)=><div key={industry}><span>↗</span>{industry}</div>)}</div><p className="industry-note">La aplicación concreta depende del proceso, la información disponible y el alcance definido con cada empresa. No afirmamos experiencia previa en un sector hasta contar con una implementación verificable.</p></div></section>

    <section className="enterprise-section" id="ia-empresas"><div className="wrap section"><span className="eyebrow">SERVICIO 02 · IA PARA EMPRESAS</span><h2>Nosotros configuramos la tecnología.<br /><em>Tu empresa simplemente la utiliza.</em></h2><p className="enterprise-lead">Analizamos una necesidad concreta y construimos una solución práctica, sin obligarte a cambiar todo tu sistema.</p><div className="feature-grid">{aiFeatures.map(([n,title,body])=><article key={n}><span className="step">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="enterprise-quote"><h3>Simple de contratar. Adaptado a tu empresa.</h3><p>Recibís una propuesta por proyecto con instalación, licencias y soporte detallados. El plazo depende del alcance y los accesos disponibles.</p></div><a className="button" href="#contacto">Solicitar diagnóstico de automatización <span>↗</span></a></div></section>

    <section className="wrap section consulting"><div className="consulting-card"><div><span className="eyebrow">CONSULTORÍA TECNOLÓGICA</span><h2>No todas las empresas necesitan la misma automatización.</h2><p>Por eso comenzamos entendiendo el funcionamiento del negocio antes de recomendar una solución. La implementación puede crecer de forma progresiva.</p></div><a className="button" href="#contacto">Solicitar diagnóstico inicial <span>↗</span></a></div></section>

    <section className="wrap section" id="planes"><div className="section-heading"><span className="eyebrow">PLANES Y PROPUESTAS</span><h2>Elegí el alcance.<br /><em>Conocé el costo antes de activar.</em></h2><p>Actualmente trabajamos por diagnóstico y propuesta individual. Todavía no publicamos precios fijos ni activamos cobros automáticos. Toda propuesta deberá indicar configuración, mantenimiento y posibles costos de WhatsApp e IA por separado.</p></div><div className="service-grid"><article className="service-card"><h3>Atención por WhatsApp</h3><p>Evaluación del catálogo, preguntas frecuentes, permisos de Meta e intervención del equipo humano.</p><a href="#contacto" className="text-link">Solicitar evaluación ↗</a></article><article className="service-card"><h3>Automatización de procesos</h3><p>Diseño de un flujo a medida, integraciones permitidas y alcance técnico previamente acordado.</p><a href="#contacto" className="text-link">Describir mi proceso ↗</a></article></div></section>

    <section className="wrap section faq"><span className="eyebrow">TRANSPARENCIA</span><h2>Lo importante,<br /><em>sin letra pequeña.</em></h2><details><summary>¿El bot garantiza más ventas?</summary><p>No. La demostración es ilustrativa; las funciones de producción se habilitan solo después de verificar su operación. Las ventas dependen de la demanda, la oferta y la atención del negocio.</p></details><details><summary>¿Tengo que contratar los dos servicios?</summary><p>No. El bot de WhatsApp y la instalación de IA para empresas se cotizan y contratan por separado.</p></details><details><summary>¿MetaBot CR ya opera en toda Centroamérica?</summary><p>El enfoque inicial es Costa Rica, con una visión de expansión progresiva hacia Nicaragua y otros mercados de la región.</p></details><details><summary>¿Qué está disponible hoy?</summary><p>La demostración y la calculadora son exploratorias. El formulario de contacto estará disponible solamente cuando se active el almacenamiento seguro. La conexión real de WhatsApp, el portal de clientes y las integraciones todavía necesitan configuración, permisos y pruebas.</p></details></section>

    <section className="closing" id="contacto"><span className="eyebrow">COSTA RICA · VISIÓN CENTROAMÉRICA</span><h2>Prepará tu empresa<br />para la nueva forma <em>de trabajar.</em></h2><p>La inteligencia artificial puede incorporarse progresivamente a los procesos de una empresa. El primer paso es identificar dónde puede aportar mayor valor.</p><SalesLeadForm enabled={isPublicLeadCaptureEnabled()} /></section>

    <footer className="wrap"><div><a className="brand" href="#inicio"><span className="brand-icon">m</span><span>MetaBot <b>CR</b></span></a><p>Inteligencia artificial y automatización para empresas.</p></div><nav aria-label="Enlaces del pie de página"><a href="#soluciones">Soluciones</a><a href="#whatsapp-ia">WhatsApp IA</a><a href="#ia-empresas">IA para empresas</a><a href="#demo">Demostración</a><a href="#contacto">Contacto</a><a href="/privacidad">Privacidad</a></nav><small>Costa Rica · Visión Centroamérica<br />MetaBot CR es una marca independiente, sin afiliación con Meta.</small></footer>
  </main>;
}
